server:
  port: 8081
spring:
  profiles:
    active: @active@
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    # 返回给前端的 JSON 去除 null 值属性
    default-property-inclusion: non_null
  # sa-token配置
  sa-token:
    # token前缀
    tokenPrefix: Bearer
    # token名称 (同时也是cookie名称)
    token-name: Authorization
    # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
    is-concurrent: false
    # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
    is-share: false
    # token风格
    token-style: simple-uuid
    # 是否在初始化配置时打印版本字符画
    is-print: false
mybatis-plus:
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型 默认使用雪花ID
      id-type: AUTO
      insert-strategy: not_null
      update-strategy: not_null
      select-strategy: not_empty
      # 逻辑删除实体字段名 或在实体属性添加@TableLogic
      logic-delete-field: flag
      # 逻辑删除全局值（1表示已删除，这也是Mybatis Plus的默认配置）
      logic-delete-value: 1
      # 逻辑未删除全局值（0表示未删除，这也是Mybatis Plus的默认配置）
      logic-not-delete-value: 0
  configuration:
    # 开启自动驼峰命名规则映射 表字段名`a_b`映射为Java属性`aB`
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.ddcat.entity,com.ddcat.entity.**
