spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.164.128:3306/ddcat?${mysql-param}
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000
      auto-commit: true
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      idle-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 15
  redis:
    # Redis服务器地址
    host: 192.168.164.128
    # 连接超时时间 毫秒
    timeout: 1000
# MySQL参数
# useAffectedRows 使用受影响行数替代匹配行数返回
# serverTimezone 默认UTC 时区
# allowMultiQueries 默认false SQL语句可携带分号
# allowPublicKeyRetrieval 默认false 允许客户端从服务器获取公钥
mysql-param: useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false&useAffectedRows=true&serverTimezone=GMT&allowMultiQueries=true&allowPublicKeyRetrieval=true
# 测试环境开启日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
file:
  # 访问前缀
  prefix: http://localhost:8080/file/ddcat/
  # 服务器存储路径
  path: /data/ddcat/
