server:
  port: 8081
spring:
  profiles:
    active: @active@
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    # 返回给前端的 JSON 去除 null 值属性
    default-property-inclusion: non_null
mybatis-plus:
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型 默认使用雪花ID
      id-type: AUTO
      where-strategy: not_empty
      # 逻辑删除实体字段名 或在实体属性添加@TableLogic
      logic-delete-field: flag
  configuration:
    # 开启自动驼峰命名规则映射 表字段名`a_b`映射为Java属性`aB`
    map-underscore-to-camel-case: true
  type-aliases-package: com.ddcat.entity.**
# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: token
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: simple-uuid
  # 是否在初始化配置时打印版本字符画
  is-print: false
ddcat:
  upload:
    # 访问前缀
    prefix: http://192.168.164.128/file/
    # 服务器存储路径
    path: /data/file/
  # SFTP
  jsch:
    host: 192.168.164.128
    port: 22
    user: root
    password: 123456
